apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  selector:
    matchLabels:
      app: hello-label
  template:
    metadata:
      labels:
        app: hello-label
    spec:
      containers:
        - name: cont-hello
          image: gcr.io/google-samples/hello-app:2.0
          env:
            - name: "PORT"
              value: "80"
